spring.ai:
  openai:
    api-key: ${OPENAI_API_KEY}
    model: gpt-4-1106-preview
  ollama:
    baseUrl: "http://onyx.local:11434"
    model: llama2

logging:
  level:
    com.marsraver: DEBUG
server:
  port: 7071

management.tracing.sampling.probability: 1.0
tracing.url: "http://localhost:4317"